# Generated by Django 5.1.1 on 2024-11-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(related_name='product', to='storeapp.product'),
        ),
        migrations.DeleteModel(
            name='ProductOrder',
        ),
    ]
