# Generated by Django 5.1.1 on 2024-11-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_remove_product_discount_remove_order_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.ManyToManyField(default=None, related_name='order', to='storeapp.order'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductOrder',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(default=None, related_name='product', to='storeapp.product'),
        ),
    ]
