# Generated by Django 5.1.3 on 2024-11-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0004_popularproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('promotion_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('discount', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='PopularProducts',
            new_name='PopularProduct',
        ),
    ]
