# Generated by Django 5.1.3 on 2024-11-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0005_promotion_rename_popularproducts_popularproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
