# Generated by Django 5.1.1 on 2024-11-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0005_dealer_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='adress',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
