# Generated by Django 5.1.3 on 2024-11-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0006_promotion_message_alter_promotion_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='applies_to_category',
            field=models.ManyToManyField(blank=True, default=None, related_name='applies_to_category', to='storeapp.category'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='applies_to_dealer',
            field=models.ManyToManyField(blank=True, default=None, related_name='applies_to_dealer', to='storeapp.dealer'),
        ),
    ]
