# Generated by Django 5.1.1 on 2024-11-07 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0006_alter_dealer_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealer',
            old_name='adress',
            new_name='address',
        ),
    ]
