# Generated by Django 5.1.3 on 2024-11-30 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0007_promotion_applies_to_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='applies_to_category',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='applies_to_dealer',
        ),
        migrations.AddField(
            model_name='promotion',
            name='applies_to_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storeapp.category'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='applies_to_dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storeapp.dealer'),
        ),
    ]
