# Generated by Django 5.1.3 on 2024-12-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0009_remove_promotion_applies_to_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
